### ISSUE TITLE
Interface conversion error in `authentik_stage_authenticator_validate` when using `configuration_stages`

### ISSUE THREAD

**Issue by mittler-works** [goauthentik/terraform-provider-authentik#376]
If you want to setup an authenticator validation stage which forces a user to configure an authenticator if none is present, you have to define configuration stages.

If you do so, the plugin crashes. Here is a minimal example to reproduce:

```terraform
# Declare provider
terraform {
  required_providers {
    authentik = {
      source = "goauthentik/authentik"
      version = "2023.5.0"
    }
  }
}

# Declare Variables
variable "authentik_url" { default = "http://localhost:9000/" }
variable "authentik_token" {}

# Setup provider
provider "authentik" {
  url   = var.authentik_url
  token = var.authentik_token
}

# Create TOTP setup stage
resource "authentik_stage_authenticator_totp" "demo_totp_setup" {
  name = "demo-totp-setup"
}

# Create the validation stage
resource "authentik_stage_authenticator_validate" "demo_mfa_validate" {
  name                  = "demo-mfa-validate"
  device_classes        = ["totp"]
  not_configured_action = "configure"
  configuration_stages  = [authentik_stage_authenticator_totp.demo_totp_setup.id ]
}
``` 

In this example I just use one configuration stage to keep it simple. The error occurs for all configurable authenticator setup stages (static, webauthn, totp, ...) and for any combination of them.

The error produced is as follows:
```
╷
│ Error: Plugin did not respond
│ 
│   with authentik_stage_authenticator_validate.demo_mfa_validate,
│   on main.tf line 27, in resource "authentik_stage_authenticator_validate" "demo_mfa_validate":
│   27: resource "authentik_stage_authenticator_validate" "demo_mfa_validate" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-authentik_v2023.5.0 plugin:

panic: interface conversion: interface {} is []interface {}, not []string

goroutine 56 [running]:
goauthentik.io/terraform-provider-authentik/internal/provider.resourceStageAuthenticatorValidateSchemaToProvider(0x0?)
	goauthentik.io/terraform-provider-authentik/internal/provider/resource_stage_authenticator_validate.go:62 +0x405
goauthentik.io/terraform-provider-authentik/internal/provider.resourceStageAuthenticatorValidateCreate({0x152f768, 0xc000480780}, 0x13907a4?, {0x1136280?, 0xc00000e968?})
	goauthentik.io/terraform-provider-authentik/internal/provider/resource_stage_authenticator_validate.go:76 +0x6a
goauthentik.io/terraform-provider-authentik/internal/provider.tr.func1({0x152f768, 0xc000480780}, 0x0?, {0x1136280, 0xc00000e968})
	goauthentik.io/terraform-provider-authentik/internal/provider/tracing.go:18 +0x177
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0001c0b60, {0x152f7a0, 0xc000175590}, 0xd?, {0x1136280, 0xc00000e968})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001c0b60, {0x152f7a0, 0xc000175590}, 0xc0003631e0, 0xc0005c2e00, {0x1136280, 0xc00000e968})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000311368, {0x152f7a0?, 0xc000175470?}, 0xc0005ae550)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000543680, {0x152f7a0?, 0xc000174ae0?}, 0xc000210230)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1302be0?, 0xc000543680}, {0x152f7a0, 0xc000174ae0}, 0xc000210000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x1532660, 0xc0007029c0}, 0xc0005f4900, 0xc00025af30, 0x1d8b720, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x1532660, 0xc0007029c0}, 0xc0005f4900, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-authentik_v2023.5.0 plugin crashed!

```

**Comment by mittler-works** [comment]
Wow, if you fix Issues even faster, you'll soon start moving backwards in time. :joy:
