### ISSUE TITLE
modifying authentik_stage_authenticator_validate crashes terraform plugin

### ISSUE THREAD

**Issue by rasschaert** [goauthentik/terraform-provider-authentik#380]
Using this resource declaration, I'm removing the "webauthn" device class from a authenticator validate stage.

```
resource "authentik_stage_authenticator_validate" "my-authentication-mfa-validation" {
  configuration_stages  = [data.authentik_stage.default-authenticator-totp-setup.id, ]
  device_classes        = ["totp", ]
  last_auth_threshold   = "seconds=0"
  name                  = "my-authentication-mfa-validation"
  not_configured_action = "configure"
```

```
Terraform will perform the following actions:

  # authentik_stage_authenticator_validate.my-authentication-mfa-validation will be updated in-place
  ~ resource "authentik_stage_authenticator_validate" "my-authentication-mfa-validation" {
      ~ device_classes        = [
            "totp",
          - "webauthn",
        ]
        id                    = "133294b9-4e3c-4ac6-b24e-2153b7412fca"
        name                  = "my-authentication-mfa-validation"
        # (3 unchanged attributes hidden)
    }
```

Applying this change (and as far as I can tell, any change) to this resource crashes the plugin.

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

authentik_stage_authenticator_validate.my-authentication-mfa-validation: Modifying... [id=133294b9-4e3c-4ac6-b24e-2153b7412fca]
authentik_stage_identification.my-authentication-identification: Modifying... [id=e742627a-b9a7-4331-93be-30d98328fd8f]
╷
│ Error: Plugin did not respond
│ 
│   with authentik_stage_identification.my-authentication-identification,
│   on stages.tf line 108, in resource "authentik_stage_identification" "my-authentication-identification":
│  108: resource "authentik_stage_identification" "my-authentication-identification" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with authentik_stage_authenticator_validate.my-authentication-mfa-validation,
│   on stages.tf line 122, in resource "authentik_stage_authenticator_validate" "my-authentication-mfa-validation":
│  122: resource "authentik_stage_authenticator_validate" "my-authentication-mfa-validation" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-authentik_v2023.5.0 plugin:

panic: interface conversion: interface {} is []interface {}, not []string

goroutine 84 [running]:
goauthentik.io/terraform-provider-authentik/internal/provider.resourceStageAuthenticatorValidateSchemaToProvider(0x0?)
        goauthentik.io/terraform-provider-authentik/internal/provider/resource_stage_authenticator_validate.go:62 +0x3ec
goauthentik.io/terraform-provider-authentik/internal/provider.resourceStageAuthenticatorValidateUpdate({0x105751308, 0x140000af6e0}, 0x1400060a500, {0x105502220?, 0x1400011a260?})
        goauthentik.io/terraform-provider-authentik/internal/provider/resource_stage_authenticator_validate.go:109 +0x60
goauthentik.io/terraform-provider-authentik/internal/provider.tr.func3({0x105751308, 0x140000af6e0}, 0x0?, {0x105502220, 0x1400011a260})
        goauthentik.io/terraform-provider-authentik/internal/provider/tracing.go:30 +0x11c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x1400018aa80, {0x105751340, 0x1400007f8c0}, 0xd?, {0x105502220, 0x1400011a260})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:741 +0xec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400018aa80, {0x105751340, 0x1400007f8c0}, 0x140004df2b0, 0x1400060a380, {0x105502220, 0x1400011a260})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x680
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400000c0f0, {0x105751340?, 0x1400007f7a0?}, 0x14000717ae0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xb94
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140004e5360, {0x105751340?, 0x14000281ec0?}, 0x140003a9260)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1056cfa00?, 0x140004e5360}, {0x105751340, 0x14000281ec0}, 0x140003a91f0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000010000, {0x1057541a0, 0x140007024e0}, 0x140004ff200, 0x1400007ee70, 0x105f88700, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xb90
google.golang.org/grpc.(*Server).handleStream(0x14000010000, {0x1057541a0, 0x140007024e0}, 0x140004ff200, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x298

Error: The terraform-provider-authentik_v2023.5.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

After making the necessary change in the web UI, Terraform is happy to leave it alone.

**Comment by BeryJu** [comment]
Fixed by https://github.com/goauthentik/terraform-provider-authentik/commit/a341ff61b04067cabf3711af0cf4f6d0fbdd5694
